
#hash: wl3km6sudnvqtlfq4a2it6a4yi
#path: C:\Users\shirao\distb\facebook.zstd\wl3km6sudnvqtlfq4a2it6a4yi
[facebook.zstd]
version = "1.5.7"
options.legacy_support = true
options.build_compression = true
options.programs_link_shared = false
options.build_decompression = true
options.multi_thread_support = true
options.build_program = false
options.lz4_support = false
options.lzma_support = false
options.shared = false
options.static = true
options.use_static_runtime = false
options.zlib_support = false



